language: ruby

rvm:
  - 2.1.6

cache: bundler

install:
  - bundle install

before_script:
  - "chmod +x ./build.sh"

script:
  "./build.sh"

branches:
  only:
    - master

env:
  global:
    secure: "NoAMFVFdoYeG5WlGBW3ZzEAs4Su13immrhILnFzE5frJMcdfEyukDEjfupeFoyOXIqqeqNDw354n8z7ecvAksyz+AwVqI+YeDETPl2NYgieUWgLjpoH4RMf0SIPQ506kfm4/kiF2LjzBWcdo1MBbWIBU9eZtDiTj34uNdvYJ4kCn8Mx0hLAPzfcSiSTIcxCCiVh8VxgU8E1D/82IIBk4Q55nAIQlap7/E8NVCPhh/H9ehr4ees7VngrnByetCbAiyd/IP5yCqyAoOvaVEDQN9/vXiBGRQFslZSxnrqB+pPjfgfHHh9nP10KVsj7nqKLNDY9aSpDHD85et8hxYP46EmlqabuVS/8gabn5/N/yMohnupBNwPFTeRZLhrI54iafiBrM2EaYcCW/6yDnFU4dE2Qu6gNTGYNIub03Ziz28nCN9of2ulZZOqswpsxYZX32qK43+Ny5p97y2F7rXNYmPGHZXvgZtNtPNbqzMusplwS2G235adCexhFiva5S/OGSTwillBCZkT+9QJlju+RwhZm77HK3xJEJzhDrkTM47sD7PdFSJgfjdfmWzy+77nUbDFefDLtD7W+MWTOHdc9R9nhpkbHRzHkiD7BGSPy8aHR5kkwXdqIiPvtGYaj4TqbGnNB35a7q0N+izTpkh2XgLuVr0+UMgTevZpROjyS6yQI="
