language: ruby

rvm:
  - 2.1.6

cache: bundler

install:
  - bundle install

script: bundle exec rake site:deploy --trace

branches:
  only:
    - master

env:
  global:
    secure: "RwzZ1H1z+0xIYWakb8Sj2HrTz4b2WqWv3snnb+sChA4PDSZQ4gkbiFBjIkXOjz2FCw2TvPkHM8xM0D2qpK7Om8BoY7hfxj43xUM31g34/CGLmik5hnEy2xNDFmt1vn46jv6kY48NodpNDWyYK5uo2X1dknV8IrYj0qaKe7JlBfVXJq7jMy4/d6yKOxL2iZlJIytL+K2OZUpbuQJtfYA8hHZCo1keZdFUfwESb3J18b6c+u2t15422wmilLAok1w1CaNNIFu0P+lMZkktGZE+9e2arIZfDKTL8lsPuvbSj9rvehIXaKIZH09WMoj/ZubbsjntlyR5smmDahvyhS3zQiHJdhRF61cDUipHLwxPL6di0GJapE7YylzV0pvOU7jKoNKJzSBIgtZnbTs9MMIcRwQ5VAfDEjNmQd1ZD5oI42BhcxmiSQv//6Nt09GOR1YrKKNGB3gzLT2LZSYI8yT3emkx0PXsqvTYks8xZjiT5mvXGakXUbxV8ETRT1UTYZq9iMZ9pFC6tHBUE0B0RsVf+mtgsdLkZuXYD5Fd12toxjl6Hb3C+9EVVSVEXvFynU0q9qNdCbrX4oHM90ezbqnOFuLtYpVCa9DkWEozBRHccBS8S9dX8GGemJX2MvgiXem6Jp2oWYFv/yflt+C8DG3HYDoK69tdWU6i+P9dGIp+KPw="
